### ISSUE TITLE
Submit to Spring Session ?

### ISSUE THREAD

**Issue by rwinch** [manderson23/spring-session-hazelcast#1]
@manderson23 Thanks for putting this sample together! I'd love to get this sample submitted to Spring Session so that others can leverage it. 

I can see two approaches:
- Updating the existing hazelcast sample to demonstrate what you have done here would be a great start.
- Submitting official support for Hazelcast would be awesome! Do you think you would be willing to contribute this?

Any chance you would be interested in contributing?

Thanks again for the great example!

**Comment by manderson23** [comment]
A PR to update the existing sample shouldn't be a problem.

What would you see official support for Hazelcast involving?

**Comment by rwinch** [comment]
@manderson23 

> A PR to update the existing sample shouldn't be a problem.

That is great to hear!

> What would you see official support for Hazelcast involving?

That is a good question. I think it would likely include:
- HazelcastSessionListener (possibly renamed to SpringEntryListener)
- An easy mechanism for configuring it within Spring. Perhaps a `@EnableHazelcastHttpSession` similar to the `@EnableRedisHttpSession`. This feature would likely depend on #231

**Comment by manderson23** [comment]
Do you have a preference for which version of Hazelcast is supported? I notice in 3.5 they have deprecated EntryListener in favour of a new MapListener (http://docs.hazelcast.org/docs/3.5/javadoc/com/hazelcast/map/listener/MapListener.html) with sub-interfaces for specific event types.

Using 3.5 isn't an issue for me in the project I'm using Hazelcast and I'm happy to update the sample to use the new interface. Are you happy to go with the latest version? Or is there anything else in the Spring ecosystem that uses Hazelcast where this could cause an issue?

**Comment by rwinch** [comment]
@manderson23 Thanks for the good question. Since Spring Session 1.1 is going to target [Spring IO Platform 2.0](http://docs.spring.io/platform/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/) I' think we should use Hazelcast 3.5.1. This will mean we don't have to support multiple versions.

**Comment by manderson23** [comment]
OK. I'll update my sample to use the new listeners added in 3.5.

**Comment by manderson23** [comment]
Added in https://github.com/spring-projects/spring-session/commit/e3414ef11eaef6446553c8f9b0ca5e86b94c1f0b
